model:
  encoder_name: resnet18
  embedding_dim: 128
  hidden_dim: 128
  num_decoder_layers: 2
  nhead: 4
  dropout: 0.1

data:
  data_dir: data
  batch_size: 16
  num_workers: 4
  train_val_test_split: [0.8, 0.1, 0.1]
  img_size: 224

training:
  seed: 42
  learning_rate: 1e-3
  max_epochs: 50