# config.yaml
defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params: {}
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]

data:
  data_dir: "data"
  img_size: 224
  batch_size: 32
  num_workers: 4
  train_val_test_split: [0.8, 0.1, 0.1]
  max_seq_len: 512

model:
  encoder_name: "vit_tiny"  # vit_tiny, vit_small, vit_base, resnet18, resnet50
  embedding_dim: 256
  hidden_dim: 256
  num_decoder_layers: 3
  nhead: 8
  dropout: 0.1
  pad_token_id: 0
  sos_token_id: 1
  eos_token_id: 2
  max_seq_len: 512

training:
  seed: 42
  max_epochs: 100
  patience: 10
  learning_rate: 1e-4
  weight_decay: 1e-4
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  gpus: 1
  precision: 16

logging:
  log_dir: "logs"
  experiment_name: "latex_ocr"
  use_wandb: False
  wandb_project: "latex-ocr"
  log_every_n_steps: 10

inference:
  model_path: "model_checkpoint.ckpt"
  image_path: "test_image.png"
  output_dir: "outputs"