data:
  img_folder: "data/images"
  annotations: "data/annotations.txt"
model:
  embed_size: 256
  hidden_size: 512
  vocab_size: 1000
  num_layers: 2
training:
  batch_size: 16
  learning_rate: 0.001
  epochs: 20